### PR TITLE
Fixed bug with ScanImage's parse_metadata so that it works properly when hStackManager is disabled

### LINKED ISSUE #372: [Bug]: invalid literal for int() 'Inf' for SI.hStackManager.framesPerSlice #1108
See https://github.com/catalystneuro/neuroconv/issues/1108

### PR DESCRIPTION
**Pull request by pauladkisson**
Fixes #372

### CODE REVIEW

**Comment by pauladkisson** [comment]
@k1o0, This should fix the bug you found.  Please let me know if you run into any more problems.

**Review by h-mayorquin — COMMENTED** [review]
This LGTM.  Two things:

* Any chance @k1o0 could test this just to be sure?
* Maybe we can stub the example file that he shared with us and add it to the examples? 

As we have many tiff based systems it might be a good investment of developer time to understand the format to the degree that we can stub so we can add this this and future examples to our testing suite. Probably this discussion deserves its own issue.

**Comment by pauladkisson** [comment]
> Maybe we can stub the example file that he shared with us and add it to the examples?

Can be tricky to stub sometimes...
In this case one of the existing examples already has SI.hStackManager.enable = "false", so I think we have it covered.

**Comment by h-mayorquin** [comment]
> > Maybe we can stub the example file that he shared with us and add it to the examples?
> 
> Can be tricky to stub sometimes... In this case one of the existing examples already has SI.hStackManager.enable = "false", so I think we have it covered.

So how come it was not failing?

**Comment by pauladkisson** [comment]
> > > Maybe we can stub the example file that he shared with us and add it to the examples?
> > 
> > 
> > Can be tricky to stub sometimes... In this case one of the existing examples already has SI.hStackManager.enable = "false", so I think we have it covered.
> 
> So how come it was not failing?

It was only testing the metadata parsing function (not e.g. get_video), and instead of Inf, it had some (presumably inaccurate) ints for num_planes and frames_per_slice.

**Comment by k1o0** [comment]
I was able to successfully extract the metadata and generate an NWB file from the tif. Happy for you to use this file as a test fixture.

**Comment by h-mayorquin** [comment]
Thanks @k1o0 
we will be merging this and storing your file. As Paul says it might be tricky to stub (basically make a shorter version of it for continuous integration purposes) but I will give it a try as soon as I can.

Thanks for reporting the issue and following up.

One final question, can you give us a bit of provenance for the file? what system was used to acquire it and whatever you remember from when you make the recording?

**Review by h-mayorquin — APPROVED** [review]

**Comment by h-mayorquin** [comment]
Ah, I see that you answered here:

https://github.com/catalystneuro/neuroconv/issues/1108#issuecomment-2407547884

Thanks a bunch.

**Pull request merged**
