### PR TITLE
Multi-Plane and Multi-Channel Support for ScanImage

### LINKED ISSUE #240: [Feature]: Multi-channel and Multi-plane support for ScanImage
### What would you like to see added to ROI Extractors?

ScanImage currently only supports single-plane and single-channel .tif files from ScanImage.  But mouseV1 data contains both multi-plane and multi-channel data.  So, ROIExtractors should support this data.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/roiextractors/blob/master/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/roiextractors/issues)?

### PR DESCRIPTION
**Pull request by pauladkisson**
Fixes #240
Continues from #241 rebased from #248

### CODE REVIEW

**Comment by pauladkisson** [comment]
The one thing that I never really figured out is how to deal with the times for the volumetric imaging.  Still not really sure how that should be represented.  Right now the times are accessible in each SinglePlaneImagingExtractor.  Other than that this should be good to go.

**Comment by CodyCBakerPhD** [comment]
> The one thing that I never really figured out is how to deal with the times for the volumetric imaging. Still not really sure how that should be represented. 

It looks like our base classes themselves still need to be updated to the latest SI standard (`get_times`) so fine to leave that as a follow-up

I know we talked about having an array of times to indicate the shifts for each plane, but for consistency with the other methods like `get_video`, I think the simplest return for such a function would just be the timestamps of the first plane capture in each volume, for each frame

Then we can talk about a separate method for volumes that returns a more detailed structure and get feedback from the rest of the team on that

**Comment by CodyCBakerPhD** [comment]
This LGTM, very well tested!

@alessandratrapani How does it look to you?

**Review by alessandratrapani — APPROVED** [review]
Looks good to me too, we were discussing about it just few minutes ago and I think this should work properly!

**Pull request merged**
