### PR TITLE
Memap changes

### PR DESCRIPTION
**Pull request by Saksham20**
2 small changes in the base class:

1. 
- `get_traces()`,` get_images_dict()` keep memory mapped images/dict by child classes. 
- get_roi_locations: reads only those `roi_image_masks `for the requested `roi_ids `and finds their locations. Before: it loaded the whole 
   of image_mask and indexed into that using the `roi_ids`. 
2. 
- better indexing of requested roi_ids (using `list.index()`)

### CODE REVIEW

**Comment by bendichter** [comment]
@Saksham20 can you look into what's going on with the CI?

**Comment by Saksham20** [comment]
> @Saksham20 can you look into what's going on with the CI?

Yes, I'm on it, some git annex issue with gin, 
All tests pass on my machine though

**Comment by bendichter** [comment]
OK, if tests pass on your machine that can work as a proxy for now, but I do want to try to sort out the datalad issues asap. May require filing an issue. Is this ready to merge?

**Comment by Saksham20** [comment]
> OK, if tests pass on your machine that can work as a proxy for now, but I do want to try to sort out the datalad issues asap. May require filing an issue. Is this ready to merge?

yes its ready

**Comment by bendichter** [comment]
Can you try pegging datalad to an earlier release?

**Pull request merged**
