### PR TITLE
Remove NWB write functions; throw error with instructions

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Removal of local NWB write function logic, but maintaining the function itself which throws the following error with instructions

image

I can set a notification 3 months from now to actually remove the methods themselves, if that timeline works for you all.

Exact message instructions may depend on the upcoming tool/import re-organization, which is why I'm setting this to draft for the moment.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
To-Do before next release

- [ ] fix tests

**Comment by CodyCBakerPhD** [comment]
@alejoe91 Ready for review

**Comment by bendichter** [comment]
Looks good overall, but test names e.g. `test_convert_img_interface_to_nwb` need to change

**Review by bendichter — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
@bendichter Note the tests occasionally do test roundtrip write within their own format - I restored the roundtrip check for this now. So test suite is 'mostly' read, but 'some' write where applicable.

**Comment by bendichter** [comment]
ok, sounds good

**Comment by CodyCBakerPhD** [comment]
@bendichter Oh my, it actually seems that roundtrip checking of available non-NWB write methods fails. I've commented it out for now and I'll raise an issue for it.

**Pull request merged**
