### PR TITLE
drop python 3.8

### PR DESCRIPTION
**Pull request by bendichter**

### CODE REVIEW

**Comment by h-mayorquin** [comment]
Tests are not running for some reason.

**Comment by bendichter** [comment]
@h-mayorquin the only tests that are not running are the 3.8 tests, since are are removing Python 3.8 support

**Comment by bendichter** [comment]
@h-mayorquin there, I fixed it and made those tests no longer required

**Comment by h-mayorquin** [comment]
> @h-mayorquin the only tests that are not running are the 3.8 tests, since are are removing Python 3.8 support

No, 10 minutes ago some runners (probably mac) were not assigned yet. I thought they were hanging but probably was just a big queue. Good they are done anyway.

**Review by h-mayorquin — APPROVED** [review]

**Pull request merged**
