### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by pauladkisson**
Update Readme to conform to neuroconv's style

See #282 to see how info from the developer guide section is now included in the documentation

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
As discussed, while we're improving this README overall, let's

a) standardize appearance to be consistent with our other main packages; probably mimic NeuroConv's README as much as possible

b) would be nice to have a brand logo for this project at some point

c) replace first one-liner with the 'functionality' description

d) embed a subrange of the ecosystem format support table tabs to display format support so we have fewer places that need to remember to update it over time (just the ophys ones); work with @garrettmflynn on how to do that

e) move example datasets part to developer guide docs

f) move SIMA troubleshooting to somewhere in the main docs

**Comment by pauladkisson** [comment]
> would be nice to have a brand logo for this project at some point
See #281

**Comment by pauladkisson** [comment]
> embed a subrange of the ecosystem format support table tabs to display format support so we have fewer places that need to remember to update it over time (just the ophys ones)

I added the link as it appears in NWB GUIDE, but it doesn't render automatically on github and trying to build the docs locally throws an error. So I can't easily check the solution.

**Comment by CodyCBakerPhD** [comment]
> I added the link as it appears in NWB GUIDE, but it doesn't render automatically on github and trying to build the docs locally throws an error. So I can't easily check the solution.

Possibly related to configuration (which file is also as out of date as the README... https://github.com/catalystneuro/roiextractors/blob/d12132231466ae3ddf4dc0efc99ad68e602078cf/docs/source/conf.py)

I would say splinter off the changes to `docs` from this PR to a new one, and this PR can just be the README update; unless you'd rather combine the two here?

In the side PR I'd also update to pydata theme while we're at it; it gives a lot of extra width room that is great for stuff like this

Oh, also looks like we're not building RTD on PRs here, so I enabled that so we can see a full log of errors more easily

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
