### PR TITLE
added dailies with email notifs

### PR DESCRIPTION
**Pull request by pauladkisson**

### CODE REVIEW

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
@pauladkisson Cool, and you set yourself in the `DAILY_FAILURE_EMAIL_LIST`?

**Comment by pauladkisson** [comment]
yeah idk if the syntax is right but the secret is 
'paul.wesley.adkisson@gmail.com'
(not including quote marks)

**Comment by CodyCBakerPhD** [comment]
KK should work then but keep an eye if not

Also this PR shows those wheel issues I mentioned

**Comment by pauladkisson** [comment]
Yeah I see that, lemme see if i can fix it real quick

**Comment by pauladkisson** [comment]
Actually, let's merge this first while the tests are failing so I can check the workflow

**Pull request merged**
