### PR TITLE
Memmap extractor unification II

### PR DESCRIPTION
**Pull request by h-mayorquin**
This PR is a follow up #122  and has it as its base. 
It implements the following things:

1) The `VideoStructure` data class now implements a method `transform_video_to_canonical_form` that converts a video with a the given structure to the canonical form `(num_frames, rows, columns, num_channels)`. A condition was added into the `test_extraction_tools` that test this functionality.

2) `NumpyMemmapImagingExtractor` now transforms its video to the canonical form and the methods (including `write_imaging` in `MemmapImagingExtractor`) are refactored to account for this.

3) All the methods of `NumpyMemmapImagingExtractor` are moved to the abstract `MemmapImagingExtractor` class.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Don't forget to change PR bases for chained PR's - simplifies changelog and can also help indicate when the branch is out of date of parent

**Comment by h-mayorquin** [comment]
> @h-mayorquin Don't forget to change PR bases for chained PR's - simplifies changelog and can also help indicate when the branch is out of date of parent

Do you do this from here (the visual interface)? 
I sort of thought that branching from the right place would take care of this.

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD is there anything missing here?

**Review by CodyCBakerPhD — DISMISSED** [review]

**Comment by CodyCBakerPhD** [comment]
> @CodyCBakerPhD is there anything missing here?

@h-mayorquin Tests failing as of https://github.com/catalystneuro/roiextractors/pull/125/commits/cd77055ea2206d1fca6b77bb22a36eadf1919d0f

**Comment by h-mayorquin** [comment]
> > @CodyCBakerPhD is there anything missing here?
> 
> @h-mayorquin Tests failing as of [cd77055](https://github.com/catalystneuro/roiextractors/commit/cd77055ea2206d1fca6b77bb22a36eadf1919d0f)

Yes, removed the zarr import incorrectly. It should be working now.

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
